package symboltable.ast.expressionnodes.binaryexpressions.numtobool;

import symboltable.ast.expressionnodes.binaryexpressions.NumberToBooleanBinaryExpressionNode;

public class GreaterEqualExpressionNode extends NumberToBooleanBinaryExpressionNode {
}
