package utility;

public enum TokenType {
    id_class,
    id_method_variable,
    literal_int,
    literal_char,
    literal_string,
    literal_bool,
    literal_null,
    punctuation_open_parenthesis,
    punctuation_close_parenthesis,
    punctuation_open_curly,
    punctuation_close_curly,
    punctuation_semicolon,
    punctuation_colon,
    punctuation_comma,
    operand_greater,
    operand_greater_equal,
    operand_lesser,
    operand_lesser_equal,
    operand_equals,
    operand_not_equals,
    operand_not,
    operand_and,
    operand_or,
    operand_plus,
    operand_minus,
    operand_times,
    operand_division,
    operand_modulus,
    assign_normal,
    assign_plus,
    assign_minus,
    eof,
    other
}
